// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tylokxsivptfcgfdzsfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bG9reHNpdnB0ZmNnZmR6c2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjk4NTMsImV4cCI6MjA3Nzc0NTg1M30.VEdgiGG91H5QF4VsOvwUtG25jrPYJ7vvhVMmbPmh1UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});